version: '3.4'

services:
 api_docker:
  image: dockerapi:latests
  depends_on:
   - postgres_image
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8000:80"
  environment:
   DB_CONNECTION_STRING: "host=postgres_image;port=5432;database=dbcategorias;username=user;password=pass"


 postgres_image:
  image: postgres:latest
  ports:
   - "5432:5432"
  restart: always
  environment:
   POSTGRES_USER: user
   POSTGRES_PASSWORD: pass
   POSTGRES_DB: dbcategorias
